### ISSUE TITLE
BodyEditor Libgdx Demo doesn't work, GdxRuntimeException:NoSuchMethodError

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MovingBlocks/box2d-editor#25]
```
What steps will reproduce the problem?
1.Create a Libgdx project and add the loaders of physics-body-editor-2.9.2.zip 
to the libs directory of the project.
2.Replace the source files with the files from bodyeditor-libgdx-demo-2.9.1.zip.
3.Run on Android or Desktop.

What is the expected output? What do you see instead?
I didn't see the result which looks like what physics-body-editor.jar from the 
physics-body-editor-2.9.2 has produced.
Instead, a GdxRuntimeException occurred.

What version of the product are you using? On what operating system?
physics-body-editor-2.9.2.zip
bodyeditor-libgdx-demo-2.9.1.zip
libgdx-nightly-20130430.zip
Windows 8 Enterprise 64 bit

Please provide any additional information below.
Exception in thread "LWJGL Application" 
com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: 
com.badlogic.gdx.utils.JsonReader.parse(Ljava/lang/String;)Ljava/lang/Object;
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:116)
Caused by: java.lang.NoSuchMethodError: 
com.badlogic.gdx.utils.JsonReader.parse(Ljava/lang/String;)Ljava/lang/Object;
    at aurelienribon.bodyeditor.BodyEditorLoader.readJson(BodyEditorLoader.java:179)
    at aurelienribon.bodyeditor.BodyEditorLoader.<init>(BodyEditorLoader.java:41)
    at aurelienribon.bodyeditor.App.createBottle(App.java:126)
    at aurelienribon.bodyeditor.App.create(App.java:73)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:130)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:110)

```

Original issue reported on code.google.com by `wy.willi...@gmail.com` on 2 May 2013 at 2:27
##

**Comment by vampcat** [comment]
@Cervator I believe this issue can now be closed, on account of being too outdated to be relevant?

**Comment by charlmert** [comment]
Thanks! worked for me too
