### ISSUE TITLE
Execution failed for task ':loader-libgdx-demo:run'. The window goes blank.

### ISSUE THREAD

**Issue by jozefcifre** [MovingBlocks/box2d-editor#50]
Version: cloned today from develop branch
Distro: NixOS

[nix-shell] $ `./gradlew run` cout:

```
Configuration on demand is an incubating feature.

> Task :editor:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :editor:processResources
> Task :editor:classes

> Task :editor:run
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/jvucq/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.3/3df168ac74e4a8c96562cdff24ad352e255bf89c/lwjgl-2.9.3.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
LwjglGraphics: created OpenGL 3.2+ core profile (GLES 3.0) context. This is experimental!
java.lang.NullPointerException
	at aurelienribon.bodyeditor.canvas.CanvasDrawer.drawShapes(CanvasDrawer.java:213)
	at aurelienribon.bodyeditor.canvas.CanvasDrawer.drawModel(CanvasDrawer.java:71)
	at aurelienribon.bodyeditor.canvas.rigidbodies.RigidBodiesScreen.render(RigidBodiesScreen.java:414)
	at aurelienribon.bodyeditor.canvas.Canvas.render(Canvas.java:132)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:267)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

> Task :loader-libgdx:compileJava
> Task :loader-libgdx:processResources NO-SOURCE
> Task :loader-libgdx:classes
> Task :loader-libgdx:jar
> Task :loader-libgdx-demo:compileJava
> Task :loader-libgdx-demo:processResources
> Task :loader-libgdx-demo:classes

> Task :loader-libgdx-demo:run
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/jvucq/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.3/3df168ac74e4a8c96562cdff24ad352e255bf89c/lwjgl-2.9.3.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :loader-libgdx-demo:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':loader-libgdx-demo:run'.
> Process 'command '/nix/store/586r3k3ap7c0sc23dvd568hrwxipba8y-openjdk-11.0.19+7/lib/openjdk/bin/java'' finished with non-zero exit value 255

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 11m 46s
8 actionable tasks: 8 executed
```

The main window goes blank. This always happens right after I press tab to switch modes while I am on Edition mode and editing a vertex.

**Comment by BenjaminAmos** [comment]
I can reproduce this. Interestingly, I get a slightly nicer error (it looks like the same cause):
```stacktrace
java.lang.NullPointerException: Cannot read field "x" because "nextPoint" is null
        at aurelienribon.bodyeditor.canvas.CanvasDrawer.drawShapes(CanvasDrawer.java:213)
        at aurelienribon.bodyeditor.canvas.CanvasDrawer.drawModel(CanvasDrawer.java:71)
        at aurelienribon.bodyeditor.canvas.rigidbodies.RigidBodiesScreen.render(RigidBodiesScreen.java:414)
        at aurelienribon.bodyeditor.canvas.Canvas.render(Canvas.java:132)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:267)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I managed to trigger it when I tried to switch to "Edition" mode whilst in the middle of creating a new line in "Creation" mode.
